spring.application.name=agri-chatbot
server.port=8080
weather.api.key=e586a5f5d3921ebee356a279f7d4a1ad
weather.api.url=https://api.openweathermap.org/data/2.5/weather
gemini.api.key=AIzaSyCaLQiEmxa9zl3Gf4bLyFr36kljaibfv4g